#!/usr/bin/env ansible-playbook -i inventory.ini --skip-tags=bootstrap,vault
---
- hosts: all
  gather_facts: true
  become: yes
  become_user: root
  roles:
    - utils
    - shell
    - ssh-key
  tags:
    - bootstrap

- name: setup the consul servers
  hosts: consul
  gather_facts: true
  roles:
    - { role: consul, consul_is_server: yes, consul_dc: alpha, consul_ui_enabled: yes }
  tags:
    - consul
    - consul-servers

- name: setup DNSmasq
  hosts: all
  become: yes
  roles:
  - { role: dnsmasq, consul_dns_domain: bramble.local, consul_dc: alpha }
