#!/usr/bin/env ansible-playbook -i inventory.ini --skip-tags=bootstrap,vault
---
- hosts: bramble
  gather_facts: true
  become: yes
  become_user: root
  roles:
    - utils
    - shell
    - ssh-key
    - { role: dnsmasq, consul_dns_domain: bramble.local, consul_dc: alpha }
  tags:
    - bramble
    - bootstrap

- name: setup the consul servers
  hosts: consul
  gather_facts: true
  roles:
    - { role: consul, consul_is_server: yes, consul_dc: alpha, consul_bootstrap_expect: "{{ groups['consul'] | length }}", consul_ui_enabled: yes }
  tags:
    - consul
    - consul-servers
