---

- block:
  - name: install i2c tooling
    apt:
      name: "{{ item }}"
      update_cache: no
    with_items:
      - python-smbus
      - i2c-tools
    tags:
      - i2c-lcd

  - name: update the /boot/config.txt
    lineinfile:
      dest: /boot/config.txt
      line: "{{ item }}"
    with_items:
      - "device_tree="
      - "dtparam=spi=on"
      - "dtparam=i2c1=on"
      - "dtparam=i2c_arm=on"
      - "dtoverlay=w1-gpio-pullup,gpiopin=3,pullup=3"
      - "dtoverlay=w1-gpio-pullup,gpiopin=5,pullup=5"
    tags:
      - i2c-lcd

  - name: update the /etc/modules
    lineinfile:
      dest: /etc/modules
      line: "{{ item }}"
    with_items:
      - i2c_dev
      - i2c_bcm2708
    tags:
      - i2c-lcd

  become: yes
  become_user: root
