---
- name: Set authorized key took from file
  vars:
     local_home: "{{ lookup('env','HOME') }}"
  authorized_key:
    user: "{{ansible_user_id}}"
    state: present
    key: "{{ lookup('file', '{{local_home}}/.ssh/id_rsa.pub') }}"
